[valores_CN]
#ANICONS = "https://i.imgur.com/A2pPOED.png"
SNOWY = "https://i.imgur.com/KxcqKpJ.gif"
SNOW = "https://i.imgur.com/mpOU7Ca.gif"
HSNOW = "https://i.imgur.com/i5dLK8G.gif"
BSNOW = "https://i.imgur.com/4B1xuMw.gif"
SUICONS = "https://i.imgur.com/cM95ybG.jpg"
ANICONS = "https://i.imgur.com/bmUoCIb.png"
SUPPLY = "https://i.imgur.com/PWreEK2.gif"
PARADRP = "https://i.imgur.com/ShQMIoU.png"
LAND = "https://i.imgur.com/Cmyq9vd.jpg"
[folha_CN]
ANICONS = [5, 4]
SUICONS = [8, 4]
LAND = [4,8]
#CROW = [1,1]

[c_GEM]
img=".i.CN._LAND.3"

[c_CROW]
img=".i.CN._LAND.2"

[c_CROW.e_tent]
img="*fa fa-campground fa-5x"
x=900
y=300
w=100
h=100
texto="Voltaremos ao campo base"
foi=".i.ROOT.0.0"

[c_ROOT]
#img="https://i.imgur.com/Cmyq9vd.jpg"
img=".i.CN._LAND.1"

[c_ROOT.e_gem]
img="*fa fa-gem fa-5x"
x=900
y=300
w=100
h=100
texto="Talvez tenha um tesouro"
foi=".i.GEM.0.0"

[c_ROOT.e_crow]
img="*fa fa-crow fa-5x"
x=800
y=300
w=100
h=100
foi=".i.CROW.0.0"
texto="Me parece um p√°ssaro distante"
[c_ROOT.e_ping]
#img="https://i.imgur.com/bmUoCIb.png"
img=".i.CN._ANICONS.1"
x=700
y=300
w=64
h=64
o=0.5
index=1
b=4
texto="Me parece um animal distante"